"""drop admin column

Revision ID: c0ae941ac85a
Revises: 6e9c39749858
Create Date: 2024-09-07 12:58:25.098934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0ae941ac85a'
down_revision = '6e9c39749858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('rule')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rule', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
